checks:
  javascript: true
  php: true

build:
  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run
        - js-scrutinizer-run

  dependencies:
    override:
      - npm install -g yarn && yarn && yarn install

filter:
  paths: ["src/*", "tests/*"]
