language: php

dist: trusty

env:
  global:
    - TRAVIS_NODE_VERSION="10"

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.7.x-dev PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.2
      env: DB=MYSQL CORE_RELEASE=3.7.x-dev PHPUNIT_TEST=1
    - php: 7.3
      env: DB=PGSQL CORE_RELEASE=3.7.x-dev PHPUNIT_COVERAGE_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src tests; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -F php; fi
